### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by proustibat** [satotka/sonar-scanner#1]
Hi, 

I try to use it. The command is correctly ran but I get the following error:
`ERROR: Invalid value of sonar.sources for xebia-xke-testcafe-basics` as you can see here:

```
Status: Downloaded newer image for satotka/sonar-scanner:latest
INFO: Scanner configuration file: /sonar-scanner-3.2.0.1227/conf/sonar-scanner.properties
INFO: Project root configuration file: NONE
INFO: SonarQube Scanner 3.2.0.1227
INFO: Java 1.8.0_171 Oracle Corporation (64-bit)
INFO: Linux 4.10.0-35-generic amd64
INFO: SONAR_SCANNER_OPTS=-Xms1024m -Xmx1024m
INFO: User cache: /root/.sonar/cache
INFO: SonarQube server 7.7.0
INFO: Default locale: "en_US", source code encoding: "UTF-8" (analysis is platform dependent)
INFO: Load global settings
INFO: Load global settings (done) | time=651ms
INFO: Server id: BD367519-AWHW8ct9-T_TB3XqouNu
INFO: User cache: /root/.sonar/cache
INFO: Load/download plugins
INFO: Load plugins index
INFO: Load plugins index (done) | time=272ms
INFO: Load/download plugins (done) | time=36565ms
INFO: Loaded core extensions: developer-scanner
INFO: Process project properties
ERROR: Invalid value of sonar.sources for xebia-xke-testcafe-basics
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 42.780s
INFO: Final Memory: 29M/981M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
ERROR: The folder 'src' does not exist for 'xebia-xke-testcafe-basics' (base directory = /workspace)
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
Exited with code 1
```

Here is my CircleCi config: 
```
version: 2
jobs:
  build:
    working_directory: /home/circleci/project

    docker:
      - image: circleci/node:8-browsers
      - image: satotka/sonar-scanner

      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Sonar Scanner
          command: |
            docker run --rm --volume $(pwd):/workspace satotka/sonar-scanner -Dsonar.sources=src -Dsonar.projectName="xebia-xke-testcafe-basics" -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN -Dsonar.projectVersion=0.0.1 -Dsonar.projectKey=xebia-xke-testcafe-basics

```

Could you explain how we can configure our CircleCI setup to use your docker image?

Thanks a lot

**Comment by proustibat** [comment]
I finally succeed to run the analysis with the following command:
```
- run:
    name: Sonar Scanner
    command: |
      docker run --rm --volume $CIRCLE_WORKING_DIRECTORY:/workspace satotka/sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN -Dsonar.projectVersion=0.0.1 -Dsonar.projectKey=xebia-xke-testcafe-basics -Dsonar.sources="." -Dsonar.projectName="xebia-xke-testcafe-basics" -Dsonar.organization=my-sonarcloud-organization

```

But I have an issue now about the sonar.scm.provider:
`SCM provider autodetection failed. Please use "sonar.scm.provider" to define SCM of your project, or disable the SCM Sensor in the project settings.` 
because it seems that it's not considered as a git repository. Do you have any idea?

Edit:
when setting `-Dsonar.scm.provider=hg` the scanner works but nothing is displayed on the server

**Comment by satotka** [comment]
Thank you for providing the information.

I have installed Git.

If it's an error, what about trying ```-Dsonar.scm.disabled=true```?

@proustibat

**Comment by proustibat** [comment]
I tried `-Dsonar.scm.disabled=true`, the scan works but results are empty

Actually, event if the scanner can be ran, I suspect CircleCi doesn't allow to share volumes with a docker executor.  (https://discuss.circleci.com/t/why-circleci-2-0-does-not-support-mounting-folders/11605). It could also explain why it can't see my sonar-project.properties file and why the result of the scan is empty, like if the repo contains no file.
I'm not an expert with docker but I continue to search and I'm gonna ask some help from colleagues.
I'll tell you as soon as I have solutions

**Comment by proustibat** [comment]
Great I found solution !

I run a workflow for the build, test and deploy steps on CircleCI. Then another workflow with machine executor for the docker with sonar-scanner. To keep generated coverage from the first workflow I use `persist_to_workspace` in it, and `attach_workspace` in the second. It needs a little hack on coverage/lcov.info file because of the path to files that is different than the /workspace dir of the docker image. 

Here is my circleci config file:

```
version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    working_directory: /home/circleci/project
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run unit tests with coverage
          command: yarn coverage
      - run:
          name: Clean lcov.info file for Sonar
          command: awk '{sub(/home\/circleci\/project/,"workspace")}1' coverage/lcov.info > coverage/lcov.info.temp && mv coverage/lcov.info.temp coverage/lcov.info
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - coverage
            - .git
            - src
            - sonar-project.properties
  sonar:
    machine:
      image: circleci/classic:latest
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Clone Docker sonar
          command: |
            git clone git@github.com:satotka/sonar-scanner.git satotka-sonar-scanner-docker
      - run:
          name: Build docker image
          command: |
            cd satotka-sonar-scanner-docker/3.3.0
            docker build -t sssd .
      - run:
          name: Run the sonar scanner
          command: |
            docker run -v $CIRCLE_WORKING_DIRECTORY:/workspace sssd -X -Dsonar.login=$SONAR_LOGIN

workflows:
  version: 2
  main:
    jobs:
      - build
      - sonar:
          requires:
            - build
```

Then sonar-scanner find my sonar properties file:

```
sonar.projectName=xebia-xke-testcafe-basics
sonar.projectKey=sonar-project-key
sonar.host.url=https://sonarcloud.io
sonar.organization=sonar-organization
sonar.sources=src
sonar.coverage.exclusions=src/**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
```

I guess it's probably not the best way but it works fine.
Thanks a lot for sharing your dockerfile!
